In [1]:
#Base Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
#Data Science Modelling Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [3]:
advertisingdf = pd.read_csv('advertising.csv')
advertisingdf

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country         Timestamp  Clicked on Ad  
0                   Tunisia  27/03/2016 00:53              0  
1                     Nauru  04/04/2016 01:39              0  
2                San Marino  13/03/2016 20:35              0  
3                     Italy  10/01/2016 02:31              0  
4                   Iceland  03/06/2016 03:36              0  
..                      ...               ...            ...  
995                 Lebanon  11/02/2016 21:49              1  
996  Bosnia and Herzegovina  22/04/2016 02:07              1  
997                Mongolia  01/02/2016 17:24              1  
998               Guatemala  24/03/2016 02:35              0  
999                  Brazil  03/06/2016 21:43              1  

[1000 rows x 10 columns]

In [4]:
advertisingdf.drop(['Ad Topic Line','City','Country','Timestamp'], axis = 1, inplace = True)

In [5]:
advertisingdf

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male  \
0                       68.95   35     61833.90                256.09     0   
1                       80.23   31     68441.85                193.77     1   
2                       69.47   26     59785.94                236.50     0   
3                       74.15   29     54806.18                245.89     1   
4                       68.37   35     73889.99                225.58     0   
..                        ...  ...          ...                   ...   ...   
995                     72.97   30     71384.57                208.58     1   
996                     51.30   45     67782.17                134.42     1   
997                     51.63   51     42415.72                120.37     1   
998                     55.55   19     41920.79                187.95     0   
999                     45.01   26     29875.80                178.35     0   

     Clicked on Ad  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
995              1  
996              1  
997              1  
998              0  
999              1  

[1000 rows x 6 columns]

In [6]:
advertisingdf.columns = ['DailyTimeSpentonSite', 'Age', 'AreaIncome', 
       'DailyInternetUsage', 'Male', 'ClickedonAd']

In [7]:
advertisingdf

DailyTimeSpentonSite  Age  AreaIncome  DailyInternetUsage  Male  \
0                   68.95   35    61833.90              256.09     0   
1                   80.23   31    68441.85              193.77     1   
2                   69.47   26    59785.94              236.50     0   
3                   74.15   29    54806.18              245.89     1   
4                   68.37   35    73889.99              225.58     0   
..                    ...  ...         ...                 ...   ...   
995                 72.97   30    71384.57              208.58     1   
996                 51.30   45    67782.17              134.42     1   
997                 51.63   51    42415.72              120.37     1   
998                 55.55   19    41920.79              187.95     0   
999                 45.01   26    29875.80              178.35     0   

     ClickedonAd  
0              0  
1              0  
2              0  
3              0  
4              0  
..           ...  
995            1  
996            1  
997            1  
998            0  
999            1  

[1000 rows x 6 columns]

In [8]:
X = advertisingdf.drop('ClickedonAd', axis = 1)
X

DailyTimeSpentonSite  Age  AreaIncome  DailyInternetUsage  Male
0                   68.95   35    61833.90              256.09     0
1                   80.23   31    68441.85              193.77     1
2                   69.47   26    59785.94              236.50     0
3                   74.15   29    54806.18              245.89     1
4                   68.37   35    73889.99              225.58     0
..                    ...  ...         ...                 ...   ...
995                 72.97   30    71384.57              208.58     1
996                 51.30   45    67782.17              134.42     1
997                 51.63   51    42415.72              120.37     1
998                 55.55   19    41920.79              187.95     0
999                 45.01   26    29875.80              178.35     0

[1000 rows x 5 columns]

In [9]:
Y = advertisingdf['ClickedonAd']
Y

0      0
1      0
2      0
3      0
4      0
      ..
995    1
996    1
997    1
998    0
999    1
Name: ClickedonAd, Length: 1000, dtype: int64

In [10]:
X_train, x_test, Y_train, y_test = train_test_split(X, Y, test_size = 0.25)

In [11]:
y_test

929    1
783    0
300    0
986    0
59     1
      ..
445    0
742    0
974    1
510    1
252    0
Name: ClickedonAd, Length: 250, dtype: int64

In [12]:
mylogisticmodelvariable = LogisticRegression()
mylogisticmodelvariable

LogisticRegression()

In [13]:
mylogisticmodelvariable.fit(X_train, Y_train)

LogisticRegression()

In [14]:
mylogisticmodelvariable

LogisticRegression()

In [15]:
mydecisiontreemodel = DecisionTreeClassifier()
mydecisiontreemodel

DecisionTreeClassifier()

In [16]:
mydecisiontreemodel.fit(X_train,Y_train)

DecisionTreeClassifier()

In [17]:
y_pred = mylogisticmodelvariable.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [18]:
y_preddectree = mydecisiontreemodel.predict(x_test)
y_preddectree

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [46]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [48]:
rfcmodel = RandomForestClassifier(n_estimators=50)
rfcmodel

RandomForestClassifier(n_estimators=50)

In [50]:
rfcmodel.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=50)

In [51]:
y_predrandomforest = rfcmodel.predict(x_test)
y_predrandomforest

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [52]:
clickedonpreds = pd.DataFrame()

In [53]:
clickedonpreds['YTest'] = y_test
clickedonpreds['YPredLogistic'] = y_pred
clickedonpreds['YPredDecTree'] = y_preddectree
clickedonpreds['YPredRandomForest'] = y_predrandomforest
clickedonpreds

YTest  YPredLogistic  YPredDecTree  YPredRandomForest
929      1              1             1                  1
783      0              0             0                  0
300      0              0             1                  0
986      0              0             0                  0
59       1              1             1                  1
..     ...            ...           ...                ...
445      0              0             0                  0
742      0              0             0                  0
974      1              1             1                  1
510      1              0             1                  1
252      0              0             0                  0

[250 rows x 4 columns]

In [54]:
print('No of Test prediction Errors in Logistic ' , clickedonpreds[(clickedonpreds['YTest'] != clickedonpreds['YPredLogistic'])].count()['YTest'])
print('No of Test prediction Errors in Decision tree ' , clickedonpreds[(clickedonpreds['YTest'] != clickedonpreds['YPredDecTree'])].count()['YTest'])
print('No of Test prediction Errors in Random Forest ' , clickedonpreds[(clickedonpreds['YTest'] != clickedonpreds['YPredRandomForest'])].count()['YTest'])

No of Test prediction Errors in Logistic  17
No of Test prediction Errors in Decision tree  13
No of Test prediction Errors in Random Forest  9


In [55]:
print('No of Test prediction correct in Logistic ' , clickedonpreds[(clickedonpreds['YTest'] == clickedonpreds['YPredLogistic'])].count()['YTest'])
print('No of Test prediction correct in Decision tree ' , clickedonpreds[(clickedonpreds['YTest'] == clickedonpreds['YPredDecTree'])].count()['YTest'])
print('No of Test prediction correct in Random Forest ' , clickedonpreds[(clickedonpreds['YTest'] == clickedonpreds['YPredRandomForest'])].count()['YTest'])

No of Test prediction correct in Logistic  233
No of Test prediction correct in Decision tree  237
No of Test prediction correct in Random Forest  241


In [56]:
y_predrandomforestprobabilities = rfcmodel.predict_proba(x_test)
y_predrandomforestprobabilities

array([[0.06, 0.94],
       [0.86, 0.14],
       [0.92, 0.08],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.98, 0.02],
       [1.  , 0.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.84, 0.16],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.02, 0.98],
       [0.98, 0.02],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.98, 0.02],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.96, 0.04],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.04, 0.96],
       [0.  , 1.  ],
       [0.04, 0.96],
       [0.  , 1.  ],
       [0.92, 0.08],
       [0.  , 1.  ],
       [0.98, 0.02],
       [1.  ,

In [23]:
from sklearn.metrics import classification_report

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
#LOGISTIC REGRESSION y_pred is for Logistic y_preddectree is for Decision

In [26]:
print(confusion_matrix (y_preddectree, y_test))

[[122   7]
 [  6 115]]


In [27]:
print(classification_report(y_preddectree, y_test))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95       129
           1       0.94      0.95      0.95       121

    accuracy                           0.95       250
   macro avg       0.95      0.95      0.95       250
weighted avg       0.95      0.95      0.95       250



In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_preddectree, y_test)

0.948

In [30]:
y_preddectree = mydecisiontreemodel.predict(x_test)
y_preddectree

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [31]:
z = mydecisiontreemodel.predict_proba(x_test)

In [32]:
z

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [33]:
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [34]:
y_test

929    1
783    0
300    0
986    0
59     1
      ..
445    0
742    0
974    1
510    1
252    0
Name: ClickedonAd, Length: 250, dtype: int64

In [35]:
z = mylogisticmodelvariable.predict_proba(x_test)
z

array([[5.59724193e-02, 9.44027581e-01],
       [9.16480829e-01, 8.35191712e-02],
       [9.78255563e-01, 2.17444369e-02],
       [9.78875292e-01, 2.11247083e-02],
       [2.11940695e-02, 9.78805930e-01],
       [9.01949117e-01, 9.80508828e-02],
       [4.23457792e-01, 5.76542208e-01],
       [7.44244937e-01, 2.55755063e-01],
       [9.03670763e-02, 9.09632924e-01],
       [9.87301312e-01, 1.26986884e-02],
       [9.27555749e-01, 7.24442511e-02],
       [3.49384462e-03, 9.96506155e-01],
       [9.00780702e-01, 9.92192984e-02],
       [9.67248265e-01, 3.27517346e-02],
       [9.88934957e-01, 1.10650430e-02],
       [3.49947328e-02, 9.65005267e-01],
       [1.26566351e-01, 8.73433649e-01],
       [9.72227779e-01, 2.77722207e-02],
       [4.07896031e-03, 9.95921040e-01],
       [9.41122274e-01, 5.88777263e-02],
       [1.08058704e-02, 9.89194130e-01],
       [3.58788633e-03, 9.96412114e-01],
       [4.63421814e-02, 9.53657819e-01],
       [9.54412406e-01, 4.55875940e-02],
       [8.039021

In [36]:
print(z[2][0], z[2][1], z[2][0] + z[2][1])

0.9782555630820584 0.021744436917941534 1.0


In [37]:
#Select a Threshold and see ROC/AUC curve

In [38]:
#select the probabilities for 1
print(type(z))
print(z.shape)  #250 rows and 2 columns 1st col is proba for 0  and 2nd col is proba for 1

<class 'numpy.ndarray'>
(250, 2)


In [39]:
#Probability for 1 can be got like this
z[:,1] #All rows and 1st col

array([0.94402758, 0.08351917, 0.02174444, 0.02112471, 0.97880593,
       0.09805088, 0.57654221, 0.25575506, 0.90963292, 0.01269869,
       0.07244425, 0.99650616, 0.0992193 , 0.03275173, 0.01106504,
       0.96500527, 0.87343365, 0.02777222, 0.99592104, 0.05887773,
       0.98919413, 0.99641211, 0.95365782, 0.04558759, 0.19609784,
       0.03936811, 0.05484625, 0.02688823, 0.75823885, 0.05866053,
       0.01702919, 0.69799865, 0.99466963, 0.97875963, 0.99114956,
       0.01619142, 0.0215654 , 0.9976157 , 0.99930034, 0.01490962,
       0.99698972, 0.67597177, 0.97965603, 0.99825762, 0.02131269,
       0.76897277, 0.00985686, 0.16187257, 0.04916532, 0.95561414,
       0.98633388, 0.02832806, 0.34369964, 0.03006834, 0.99499275,
       0.99671868, 0.99512103, 0.42404006, 0.0468457 , 0.14465745,
       0.99777929, 0.0123503 , 0.97626853, 0.10280011, 0.88790472,
       0.91255535, 0.03086608, 0.55853127, 0.99900438, 0.14497316,
       0.986558  , 0.94018981, 0.09238057, 0.93506036, 0.59134

In [40]:
print(X.columns)
print(mylogisticmodelvariable.coef_)

Index(['DailyTimeSpentonSite', 'Age', 'AreaIncome', 'DailyInternetUsage',
       'Male'],
      dtype='object')
[[-6.13825659e-02  2.54961585e-01 -1.08262841e-05 -2.42393604e-02
   1.09742839e-03]]


In [41]:
import pickle

In [42]:
with open("logisticregressionmode.pkl", 'wb') as file:
    pickle.dump(mylogisticmodelvariable, file)

In [43]:
with open("dectreemodel.csv", 'wb') as dectreefile:
    pickle.dump(mydecisiontreemodel, dectreefile)

In [44]:
with open("logisticregressionmode.pkl", 'rb') as modelfile:
    newlogisticmodelprovidedbyaarfa = pickle.load(modelfile)

In [45]:
newlogisticmodelprovidedbyaarfa.predict(x_test)

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)